# Generated by Django 5.0.1 on 2024-01-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='list',
        ),
    ]
