# Generated by Django 5.0.1 on 2024-01-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_shop_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='Shop',
        ),
    ]
