# Generated by Django 5.0.1 on 2024-01-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_list_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='kharid',
        ),
    ]
