# Generated by Django 5.0.1 on 2024-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_shop_kharid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kharid',
            name='img',
            field=models.ImageField(upload_to='images/%y', verbose_name='akse kharid'),
        ),
    ]
