# Generated by Django 5.0.1 on 2024-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_kharid_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kharid',
            name='img',
            field=models.ImageField(upload_to='images/%y'),
        ),
    ]
