# Generated by Django 5.0.1 on 2024-02-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_mobileno_alter_checkout_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkout',
            new_name='etelaat',
        ),
    ]
